# Generated by Django 4.0.6 on 2023-01-24 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_contact_url_alter_contact_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('published_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
