# Generated by Django 4.0.6 on 2023-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_experience_mission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
